steps:
  - name: node
    entrypoint: npm
    args: ['install']
  - name: node
    entrypoint: npm
    args: ['test']
  - name: node
    entrypoint: npm
    args: ['run', 'test-remote']
  - name: node
    entrypoint: npm
    args: ['run', 'test-sfdx-newman-collection']